name:                crypto-venues
version:             0.1.0.0
github:              "runeksvendsen/crypto-venues"
license:             BSD3
author:              "Rune K. Svendsen"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/runeksvendsen/crypto-venues#readme>

default-extensions:
- StrictData
- BangPatterns
- NoImplicitPrelude
- ScopedTypeVariables
- MultiParamTypeClasses
- ScopedTypeVariables
- OverloadedStrings
- KindSignatures
- DataKinds
- FlexibleInstances
- DeriveGeneric
- RecordWildCards
- DuplicateRecordFields
- FlexibleContexts
- DeriveFunctor
- TypeOperators

dependencies:
- base            >= 4.7    && < 5
- protolude
- safe-money
- orderbook
- hash-graph
- servant
- servant-client
- servant-server
- servant-docs
- aeson
- vector
- bytestring
- scientific
- json-schema
- pretty-show
- text
- safe
- http-client
- http-client-tls
- errors
# Venues
- http-types
- mtl
- unordered-containers
- transformers
- monad-parallel
- hashable
- deepseq   #TEST
- retry
- rate-limit
- time-units
- logging

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  crypto-venues:
    main:                Main.hs
    source-dirs:
    - app
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-venues

tests:
  crypto-venues-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-venues
    - QuickCheck
    - hspec
    - HUnit
    - tasty
    - tasty-smallcheck
    - tasty-quickcheck
    - smallcheck
    - hspec-smallcheck
    - hspec-expectations-pretty-diff
