resolver: lts-10.5

packages:
- .
- location:
    git: https://github.com/runeksvendsen/orderbook.git
    commit: 1e89783eb0bcdf7d138c9b13af98931ecb14be76
  extra-dep: true
- location:
    git: https://github.com/patrickdoc/hash-graph.git
    commit: f18b143bfbbb936806c8d33bdcbc4d8970f11391
  extra-dep: true

#- ../orderbook

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- safe-money-0.4.1
### BEGIN safe-money deps
- serialise-0.2.0.0
- xmlbf-0.2
- cborg-0.2.0.0
### END safe-money deps
- rate-limit-1.4.0
### BEGIN rate-limit deps
- time-units-1.0.0
### END rate-limit deps
- logging-3.0.5
### BEGIN test deps
- hspec-smallcheck-0.5.0  # make "shouldBe" work with "SS.property"
### END test deps

#flags:
#  safe-money:
#    xmlbf: false
#    serialise: false

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.5"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
